// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	controller "belajar-go-echo/controller"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *User) Create(user controller.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(controller.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUser creates a new instance of User. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUser(t testing.TB) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
